url: https://stain88.github.io
baseurl: 

# Site settings
title: Marc Baghdadi
email: marcbaghdadi@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
-

- name: Marc Baghdadi
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: http://twitter.com/MarcBaghdadi
    - title: github
      url: http://github.com/stain88
    - title: stack-overflow
      url: http://stackoverflow.com/users/5401364/stain88?tab=profile
    - title: linkedin
      url: https://uk.linkedin.com/in/marcbaghdadi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/MarcBaghdadi
  - title: linkedin
    url: https://uk.linkedin.com/in/marcbaghdadi
  - title: stack-overflow
    url: http://stackoverflow.com/users/5401364/stain88?tab=profile
  - title: bitbucket 
    url: http://bitbucket.org/stain88
  - title: github
    url: http://github.com/stain88

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty